### ISSUE TITLE
循環参照を明確にエラーにする

### ISSUE THREAD

**Issue by Snowman-s** [Snowman-s/Trees#19]
```
┌─┐
│A├┐
└┬┘│
 │┌┴┐
 └┤B│
  └─┘
```

をコンパイラに渡すと無限ループが発生する（予想）ので、コンパイルエラーを出す

**Comment by raiga0310** [comment]
ブロックプラグは上部に一つのみ､という制約があるため､上記の書き方は単純に引数プラグが引数ブロックのブロックプラグにならないということでエラーになると思います｡
また､どちらの引数プラグをブロックプラグとして他方のブロックに接続した場合､これもエントリポイントが見つけられないということでエラーになります｡(確認済み)

defprocなどによりコードに直接現れないような形での循環参照についてはまだ未確認です

**Comment by Snowman-s** [comment]
たしかに強制的に木になるのか、ならいいや
